### ISSUE TITLE
Issue with Data Load

### ISSUE THREAD

**Issue by ajayvaaka** [dvdstore/ds3#8]
Data load giving me following error

![image](https://user-images.githubusercontent.com/17277729/166009575-53440ea8-7216-4469-a6c2-f37fa61ceed4.png)

Environment : 
ESXi : 6.7
Win : 2019
SQL : 2019

Reference : https://www.heraflux.com/resources/howto/sql-server-benchmarking-with-dvdstore/

Thanks & Regards
Ajay Vaaka

**Comment by dmorse76** [comment]
When you're installing SQL, make sure you add Full Text Search:
https://www.mssqltips.com/sqlservertip/6841/add-full-text-search-sql-server/

**Comment by ajayvaaka** [comment]
It worked,Can you help me with next step .

![image](https://user-images.githubusercontent.com/17277729/166057474-979b5d21-1985-4ca2-ab7d-5a6dbab03486.png)

I tried using server ip /server name that i'm working with .

Thanks & Regards
Ajay Vaaka

**Comment by dmorse76** [comment]
When you run the driver without any parameters, it will tell you "Enter parameters with format --parm_name=parm_value"

So, change all your single "-" to "--"

**Comment by ajayvaaka** [comment]
Thanks for correcting it. still no luck

![image](https://user-images.githubusercontent.com/17277729/166060255-d9b8d2b2-dee8-4908-bfe5-0f5d6bd98cd5.png)

**Comment by ajayvaaka** [comment]
10.1.11.6 is there serverwhere i'm working ( win 2019; sql :2019)

**Comment by dmorse76** [comment]
The error you're getting is "Login failed for user ds3user".

It looks like the Heraflux guide you followed has some outdated instructions, specifically the part where it says "Do a find and replace in the entire file and replace ds3user with ds2user, as this is a holdover from the previous version of the benchmarking tool."  You'll need to skip that part of the guide and re-do everything, then it should work.

The ds2user -> ds3user bug was fixed back in 2017, so that Heraflux article should be updated.  I'll reach out to David Klee and let him know.

**Comment by toddmuirhead** [comment]
Error indicates that the ds3user login failed.  This probably means that it wasn't successfully created when you ran the sqlserverds35_create_all.bat script for the database.  Not sure why it would have failed, but you can run just the user creation step from ds35/sqlserverds35/build/sqlserverds35_create_user.sql script.  

David's comment came in while I was writing the above response.  Probably a better idea to re-run the whole create-all script as he recommends to make sure that everything is done correctly and it completes without errors.  If you to try just rerunning the create user script you might not be as sucessful.

David - Thanks for responding to this issue.

**Comment by ajayvaaka** [comment]
ds35/sqlserverds35/build/sqlserverds35_create_user.sql : Ran successfully
didn't changed this time  ds2user -> ds3user ; load successfully

Test result is same 

tried both ds3 & ds35
<img width="327" alt="sql_user_creation_sql" src="https://user-images.githubusercontent.com/17277729/166066086-67a7bfb0-6961-4255-867d-3346ac090cf3.PNG">
<img width="222" alt="Sql_load" src="https://user-images.githubusercontent.com/17277729/166066096-a30a7450-515f-4f5d-addd-84350bdf042b.PNG">
<img width="942" alt="test" src="https://user-images.githubusercontent.com/17277729/166066102-22b52bad-7205-4584-bbbd-727ac45ae9c6.PNG">

**Comment by dmorse76** [comment]
Make sure you have TCP/IP enabled for your SQL Server instance: https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-or-disable-a-server-network-protocol?view=sql-server-ver15#SSMSProcedure

**Comment by ajayvaaka** [comment]
<img width="276" alt="TCP check" src="https://user-images.githubusercontent.com/17277729/166071245-509137f8-1f9a-46f6-8bfc-0fe919826af8.PNG">
observed it is enabled already . just disabled->re-enabled and started services . After that also no-luck

**Comment by dmorse76** [comment]
Maybe it is a firewall or some other networking issue.  To rule that out, you could try copying ds3sqlserverdriver.exe directly to the SQL Server machine itself and run the driver directly it by specifying --target=localhost

**Comment by ajayvaaka** [comment]
i'm running on localhost , where SQL is running .

![image](https://user-images.githubusercontent.com/17277729/166077097-f9cc4680-093c-482e-b927-8e8181b31c4a.png)


Thanks & Regards
Ajay Vaaka

**Comment by toddmuirhead** [comment]
Login to the sql server managment studio as administrator and see if ds3user exists as a user under Security -> Logins.  If it does exist, delete it and rerun the script.  Now,  can you logon as user ds3user to sql server via the sql server management studio?  

If this is successful, then the user is there and the error is being caused by something else.  Try running the ds3sqlserverdriver.exe with just the target, db_size, and n_threads parameters.

If you still can't get it to work, maybe we can do a zoom call on Monday and interactively figure out what it going on.  

Thanks - Todd

**Comment by ajayvaaka** [comment]
Login to the sql server managment studio as administrator and see if ds3user exists as a user under Security -> Logins. If it does exist, delete it and rerun the script. Now, can you logon as user ds3user to sql server via the sql server management studio?

* i able to see ds3user and remove it and re-ran script . I can't login with ds3user . I'm taking guidence from my SQL team. will keep you posted after that. i belive ds3user password is empty ( that is how i'm trying)

**Comment by ajayvaaka** [comment]
i'm able to communicate now.

![image](https://user-images.githubusercontent.com/17277729/166342518-9d5bb5a4-e35a-4026-b2fd-d921dd8a05a0.png)


Can you guide me next step please. is this look accurate ?

Thanks & Regards
Ajay Vaaka

**Comment by toddmuirhead** [comment]
This message means that the Login1 stored procedure that is the first one
called with DS 3.5 does not exist.  If you built the DS 3 version of the
database, then you need to use the ds3 driver instead of the 3.5 version
that you are using here.

If you did creat the 3.5 version, then the rest of the stored procedures
probably also were not created.  I would bet that other parts didn't create
successfully either. Rerun the create all script and save all of the screen
output. If it doesn't work after rerunning the create all script, send me
the output.

What was the issue that was preventing it from connecting that you fixed?

Thanks,
Todd

**Comment by ajayvaaka** [comment]
Thanks Todd for huge help.

Worked after using ds3 driver

What was the issue that was preventing it from connecting that you fixed?
* SQL mixed mode 
*  previouly , i can't able to connect to SQL using ds3user . i make sure it worked .

Thanks & Regards
Ajay Vaaka
